export const CRIME_DOCS_TITLES = [
  "American Murder: Gabby Petito",
  "American Murder: Laci Peterson",
  "American Nightmare",
  "The Perfect Neighbor",
  "Amy Bradley Is Missing",
  "Athlete A",
  "Bad Influence: The Dark Side of Kidfluencing",
  "The Twisted Tale of Amanda Knox",
  "American Godfathers: The Five Families",
  "Don't F**k with Cats: Hunting an Internet Killer",
  "Night Stalker: The Hunt for a Serial Killer",
  "American Murder: The Family Next Door",
  "The Sons of Sam: A Descent into Darkness",
  "Jack the Ripper",
  "Conversations with a Killer: The Ted Bundy Tapes",
  "The Disappearance of Madeleine McCann",
  "House of Secrets: The Burari Deaths",
  "Abducted in Plain Sight",
  "Wild Wild Country",
  "Jeffrey Epstein: Filthy Rich",
  "Worst Roommate Ever",
  "Indian Predator: Murder in a Courtroom",
  "Crime Stories: India Detectives",
  "Delhi Crime",
  "The Indrani Mukerjea Story: Buried Truth",
  "Indian Predator: The Butcher of Delhi",
  "Beast of Bangalore: Indian Predator",
  "Indian Predator: The Diary of a Serial Killer",
  "Curry & Cyanide: The Jolly Joseph Case"
];
